### ISSUE TITLE
Todo:

### ISSUE THREAD

**Issue by n-ovesen** [hackheim/HackheimMarlin#1]
- [ ] Utfør finere kalibrering av xyz ved å kjøre ut større testprints for å få bedre målinger på avvik i størrelse
- [ ] Justere akselerasjon på x/y for å få mindre brutal risting når printeren kjører
- [ ] se om kanskje eSteps/mm på 100 er et litt vel rundt tall?
